{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "keycloak.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
{{- end }}
