apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fritzbox-dyndns.fullname" . }}-config
  labels:
    {{- include "fritzbox-dyndns.labels" . | nindent 4 }}
data:
{{ toYaml .Values.config | indent 2 }}