apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fritzbox-dyndns.fullname" . }}-config
  labels:
    {{- include "fritzbox-dyndns.labels" . | nindent 4 }}
data:
  prod.json: |+
    {
      "kubernetes":{
        "ingress":{
          "name": "{{ include "fritzbox-dyndns.fullname" . -}}",
          "namespace": "{{ include "fritzbox-dyndns.namespace" . }}"
        }
      }
    }
  {{- if .Values.customconfig.enabled }}
  local.json: |+
    {{ .Values.config | toJson  }}
  {{- end }}
