{{- if and .Values.rbac.create .Values.rbac.namespaced -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fritzbox-dyndns.fullname" . }}
  namespace: {{ include "fritzbox-dyndns.namespace" . }}
  labels:
    {{- include "fritzbox-dyndns.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["ingresses"]
  verbs: ["get", "list"]
{{- end }}
