{{- if and .Values.rbac.create .Values.rbac.namespaced -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fritzbox-dyndns.fullname" . }}
  namespace: {{ include "fritzbox-dyndns.namespace" . }}
  labels:
    {{- include "fritzbox-dyndns.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "fritzbox-dyndns.serviceAccountName" . }}
  namespace: {{ include "fritzbox-dyndns.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "fritzbox-dyndns.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
